### PR TITLE
Added a new entry to Made-in-Nigeria: A browser extension called Ijeawele. 

### PR DESCRIPTION
**Pull request by viclotana**
Added an entry for a browser extension

### CODE REVIEW

**Comment by whizkydee** [comment]
Hi!

Please make the title more descriptive. Also, what's with the reference to pull request #97?

**Comment by viclotana** [comment]
@whizkydee I have just modified the Title. 
The reference was a carry-over reference from my own merges, i have rectified it.
I added a new entry in the Made in Nigeria List at Number 97, a browser extension. Please check it out and merge

**Comment by whizkydee** [comment]
Great job! Still, title should contain what you're adding. See [contributing.md](https://github.com/acekyd/made-in-nigeria/blob/master/contributing.md).

**Comment by viclotana** [comment]
@whizkydee okay, just read it. i have adjusted the title to be descriptive enough

**Pull request merged**
