### PR TITLE
Added Fuctbase64, a library I created to convert file to base64

### PR DESCRIPTION
**Pull request by sirbootoo**
I just created the library to help people get the base 64 format of the files they upload.

### CODE REVIEW

**Comment by whizkydee** [comment]
Hi. Please make the title of this PR more descriptive.

Thanks.

**Comment by sirbootoo** [comment]
Done. I have made the PR more descriptive. Thanks

**Comment by whizkydee** [comment]
Great. I also think the description of the library is too long and not precise.

Please consider reviewing.

**Comment by sirbootoo** [comment]
Updated the description as suggested.

**Comment by whizkydee** [comment]
Hey. Sorry for replying late. I actually meant that you should change the description in the readme.

When that's done, I think we're good.

**Comment by sirbootoo** [comment]
Done edited the description of the library

**Pull request merged**
