### PR TITLE
docs: rename Deprecated to Inactive

### PR DESCRIPTION
**Pull request by rotimi-best**
Based on the conversations here. 

Fixes: https://github.com/acekyd/made-in-nigeria/issues/301

In order to implement that issue, I need to first rename `Deprecated` to `Inactive` before I can implement the tags properly.

This is because the code for fetching the README looks at the code merged into main and if this change isn't in main first we can't properly test it due to the fact I will be searching for the word `Inactive` while on main we still have `Deprecated`.

Once this PR is merged in, I will go ahead to implement adding the Inactive and Archived tag on each project depending on what's in the README

### CODE REVIEW

**Comment by acekyd** [comment]
Understood. Thinking about that - the fetching the link from the `main` branch remotely may no longer be necessary. That was important because we had the code and the readme in different branches, now that they are together in the same branch - see if you can refactor the fetch to use the local readme file it has in the file path 🤔 @rotimi-best

**Comment by acekyd** [comment]
And implement it all together in this PR.

**Comment by acekyd** [comment]
Seen this? @rotimi-best

**Comment by rotimi-best** [comment]
@acekyd oh I missed that notification.

Hmm interesting. I honestly have no idea how we would fetch it from the local README. 

Ideally we should have the data in JSON that is properly structured for mapping and rendering.

What do you think?

**Comment by acekyd** [comment]
It's alright... I'll make the update and let you know. From there you can create a new branch off `main` for the new PR.

**Comment by rotimi-best** [comment]
Sounds good, thanks 👍🏾.

There is this change to get the actual status of each repo using the Github API suggested by @kaf-lamed-beyt https://github.com/acekyd/made-in-nigeria/issues/301#issuecomment-1984069854

I am currently implementing that one using the current code that calls parses the README. 

Should I continue working on it using the README fetch or wait until you make the change to main?

**Pull request merged**
