### PR TITLE
Add: Helene UI and Berlinebot

### PR DESCRIPTION
**Pull request by Eunit99**
This PR adds:
 - **Helene-UI** - Helene UI - Minimal Conversational User Interfaces
 - **BerlineBot** - Berline is a conversational bot which discourages you from getting infatuated.

### CODE REVIEW

**Comment by saintmalik** [comment]
Looks good to me 👍

**Comment by acekyd** [comment]
Thanks @saintmalik 

Hello @Eunit99, thanks for the PR... unfortunately, the projects do not meet the requirements at this time... Take a look at the [contributing guide](https://github.com/acekyd/made-in-nigeria/blob/master/contributing.md) for guidance. Thanks.

**Comment by saintmalik** [comment]
Sorry I didn't go through the Contributing guide before giving the review

**Comment by Eunit99** [comment]
@saintmalik could you please let me know if I have to change or update anything.

I went through the contributing guide before raising the PR.

Thank you.

**Pull request closed without merging**
