### PR TITLE
chore: set revalidate to false

### LINKED ISSUE #315: Report of Constant page Reloading Issue on route https://www.madeinnigeria.dev/projects
### Issue Description

I have noticed that the **website frequently reloads itself without any apparent reason on route https://www.madeinnigeria.dev/projects ,** which disrupts the user experience and makes it difficult to navigate the content seamlessly.
This reloading issue occurs consistently across different browsers and devices, suggesting that it may be a systemic problem rather than a localized issue. I have also cleared my browser cache and cookies, but the problem persists.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

### PR DESCRIPTION
**Pull request by kaf-lamed-beyt**
## What does this PR do?

Fixes #315 

@acekyd, I noticed that this issue was our own doing. I had to inspect the page in pro, and it refreshes every `5000ms`, which was what we've asked it to do, literally. 

I wondered why it worked formerly &mdash; no refreshes when it was formerly `3000ms`. The only hypothesis I have now is because the former implementation wasn't extending [React's cache](https://react.dev/reference/react/cache). Now that the request in the hook is memoized, there's no need for the revalidation, I guess. 

Eventually, I had to set `revalidate` to false. 

This PR [Fixes #315

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

[You can check this version I deployed on netlify](https://madein9ja.netlify.app/projects)

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `npm run build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Docs if changes were necessary

### CODE REVIEW

**Comment by acekyd** [comment]
Loool are you joking? @kaf-lamed-beyt 😂 Checking it out

**Review by acekyd — APPROVED** [review]
It does seem to fix it. Do you know how we should reset the cache when new projects are added to the readme then, or that should reset on build?

**Comment by kaf-lamed-beyt** [comment]
I don't even know😂. The cache explanation is just assumption. 

But, I'm pretty sure the revalidate property is definitely what's causing the refresh.

**Comment by kaf-lamed-beyt** [comment]
> It does seem to fix it. Do you know how we should reset the cache when new projects are added to the readme then, or that should reset on build?

I think the build should reset the cache. 

If there's a way to identify the cache with a key, it would have made it easier for us to reset it manually. 

I don't know if it is possible with the `cache` module from React. But, I'll check and let you know when I find something.

**Pull request merged**
