### PR TITLE
feat: add stream2peer to showcase projects

### PR DESCRIPTION
**Pull request by tobySolutions**
## What does this PR do?

This PR adds [Stream2Peer](https://github.com/tobySolutions/stream2peer) by Tobiloba, Emmanuel and Jumo to the README.md

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Check the README.md to verify the formatting is correct and it is in the correct alphabetical order

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [ ] Ran `npm run build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Docs if changes were necessary

### CODE REVIEW

**Review by kohasummons — CHANGES_REQUESTED** [review]
Screenshot 2024-12-05 at 12 15 14

You Missed a closing square bracket, @tobySolutions.

**Review by kohasummons — CHANGES_REQUESTED** [review]
Still Missing @tobySolutions :)

> Add a closing `]` after `[@tobysolutions`

What you have:
[Stream2Peer](https://github.com/tobySolutions/stream2peer) - Stream2Peer is a decentralized video stream management platform **By [@tobySolutions(https://twitter.com/toby_solutions), [@Emmanuel](https://twitter.com/official__ceo), [@Jumo](https://twitter.com/excellencyjumo)**

What we aim for:
[Stream2Peer](https://github.com/tobySolutions/stream2peer) - Stream2Peer is a decentralized video stream management platform **By [@tobySolutions](https://twitter.com/toby_solutions), [@Emmanuel](https://twitter.com/official__ceo), [@Jumo](https://twitter.com/excellencyjumo)**

**Comment by tobySolutions** [comment]
Oh shoot! My bad @kohasummons. Thank you for calling this out!

**Comment by tobySolutions** [comment]
Updated now @kohasummons. Quick question do you actually support adding multiple contributors' links?

**Comment by kohasummons** [comment]
Yeah! The published version will display the first author listed, but you can include all contributors on GitHub.

**Comment by tobySolutions** [comment]
> Yeah! The published version will display the first author listed, but you can include all contributors on GitHub.

Sure, no problem! Thank you. I have made edits 😁.

**Pull request merged**
