### PR TITLE
ft/add bolorundurowb packages

### PR DESCRIPTION
**Pull request by bolorundurowb**
- dotenv.net
- Open Exam Suite
- moment.net
- shortid
- Git Aliases for Windows
- vCardLib
- dotnetANPR

### CODE REVIEW

**Comment by acekyd** [comment]
Hi @bolorundurowb, quite the interesting projects here. Thanks for contributing. However there are some projects in the list that do not match our current requirements. You can check it out here - [Contributing guide](https://github.com/acekyd/made-in-nigeria/blob/master/contributing.md)

**Comment by bolorundurowb** [comment]
Would address the concerns, thanks for the feedback @acekyd

**Comment by bolorundurowb** [comment]
@acekyd made the necessary changes

**Comment by acekyd** [comment]
Hey... Apologies for the delay in getting back to you on this... Was about to merge but realized the links are broken and point to twitter instead.

**Pull request closed without merging**
