### PR TITLE
chore: performance improvements, infinite scrolling.

### PR DESCRIPTION
**Pull request by kaf-lamed-beyt**
- fix hydration error on `/creators` this error occurred because I nested a button in a Chakra Box with its role set to "button" like so: (addresses #277)
```tsx
<Box as="button" onClick={loadMore}>
  <SecondaryButton />
</Box>
```
- add infinite scrolling
- improve project search.  (addresses #278)
   The former approach involved one that considers almost all the properties &mdash; `repoName`, `repoDescription`, `projectAuthor` etc &mdash; in the filter. Which in return blocked the UI, since React is still calculating how to paint the page. 
   
   Solution: I tried the `React.useCallback()` approach to handle that expensive calculation, but we still need a way to NOT fire the filter whenever a key is pressed. A good alternative I considered was to debounce the function's execution. 
   
   So now, even if we decide to search for a project with its description and any other property in the future &mdash; which I wouldn't encourage though, lol &mdash; it'd work fine.
   
@acekyd, kindly review when you see this.

### CODE REVIEW

**Comment by acekyd** [comment]
Hey @kaf-lamed-beyt. Thanks for the PR. 

- The hydration error des appear fixed. 
- Infinite scrolling seems broken though. Inconsistent and the page keeps resetting - both for projects and articles. 
- Project search is broken with this, the typed text disappears
- Only those three properties are essential - name, author and description - but I see the problem if it has to run the loop thrice on keypress. The current live implementation uses some form of angular subscription. 

In the mean time, can we revert the infinite loading / project search updates so we can have that in a different PR to figure it out properly. 

What do you think?

**Comment by kaf-lamed-beyt** [comment]
When you mean... "the page keeps resetting", you're referring to when it scrolls back to the top yes?

> Project search is broken with this, the typed text disappears

Does this happen when the page scrolls back to the top too?

> Only those three properties are essential - name, author and description - but I see the problem if it has to run the loop thrice on keypress. The current live implementation uses some form of angular subscription.

Yes, it'll impact the response time.

> In the mean time, can we revert the infinite loading / project search updates so we can have that in a different PR to figure it out properly.

Let me see if I can figure out why the reset happens. Once I find a fix, I'll push. If not, I'll revert both of them, and open a new PR to address it.

**Comment by acekyd** [comment]
Yes it scrolls back to the top, sometimes new content is added, sometimes it goes back to before any content was added. Is that not the same experience for you?

The typed text for search disappears about a second after you stopped typing. And I also just noticed the projects page keeps refreshing after every couple seconds even if you're not doing anything.

**Comment by kaf-lamed-beyt** [comment]
Scrolling back to the top before new content is added is new to me. I noticed the former, earlier on. 

The pages is refreshing now? That's weird. I'll have a look at it now and get back to you.

**Comment by kaf-lamed-beyt** [comment]
Figured out the reason why the "scroll-to-top" happens on the /creators route. 

It is a default behaviour of button elements. `event.preventDefault()` should fix it &mdash; hopefully on the projects route too.

**Comment by kaf-lamed-beyt** [comment]
Hi @acekyd, please take a look now and let me know if the issues persist. 

About the refreshes even when we're not doing anything. I did not notice anything like that. But, please let me know if it persists, nonetheless.

**Comment by acekyd** [comment]
Hey! Can you merge the current `web-dev` into this your branch? I want to test it in full but I'm on the move. @kaf-lamed-beyt

**Comment by acekyd** [comment]
Check out the deploy preview - page still reloading and hence issues still persist. 

https://deploy-preview-282--staging-madeinnigeria.netlify.app/projects

**Comment by kaf-lamed-beyt** [comment]
Huh. that's weird. Let me check if my branch is updated. 

I'll have a look at the link too.

**Comment by kaf-lamed-beyt** [comment]
My PC's battery is low now. When there's power. I'll inspect the deploy preview link. 

That aside, @acekyd, help me test it on localhost. I want to be sure the issue doesn't persist on localhost so I can know how to proceed.

**Comment by kaf-lamed-beyt** [comment]
@acekyd, apparently, omitting the `next` property in the fetch URL was the problem. Why I had it removed, I have no idea. 

```ts
const res = await fetch(
 "https://raw.githubusercontent.com/acekyd/made-in-nigeria/master/README.MD",
 { next: { revalidate: 5000 } }
);
  ```

**Comment by acekyd** [comment]
Looking great! Thank you. A few things:
- The load more articles button still goes back to top of page
- The search experience feels less optimal because it's currently only searching the title
- Reduce the font (intensity in general) of the "You have reached the end / no repositories found / no more articles" messages.

Thanks again @kaf-lamed-beyt

**Comment by kaf-lamed-beyt** [comment]
> The load more articles button still goes back to top of page

That's weird. I'll take a look at it again.

> The search experience feels less optimal because it's currently only searching the title

So, should we include other properties? Which one would you suggest &mdash: `repoDescription`, and `repoAuthor`?

>Reduce the font (intensity in general) of the "You have reached the end / no repositories found / no more articles" messages.
Noted. I'll have this changed.

**Comment by acekyd** [comment]
Yes I think just those two. @kaf-lamed-beyt

**Comment by kaf-lamed-beyt** [comment]
> Yes I think just those two. @kaf-lamed-beyt

Super!

**Comment by kaf-lamed-beyt** [comment]
@acekyd, kindly take a look now and let me know if the issues are gone.

**Comment by acekyd** [comment]
Looks great. Thanks @kaf-lamed-beyt

**Pull request merged**
